services:
  backend:
    build: ./server
    ports:
      - "8080:8080"
    networks:
      - net
    depends_on:
      - mongodb
    environment:
      - DB=mongodb://mongodb:27017/db
    volumes:
      - ./server:/app 

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    networks:
      - net
    volumes:
      - ./client:/app 

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    networks:
      - net
    volumes:
      - mongo-data:/data/db

networks:
  net:
    driver: bridge

volumes:
  mongo-data:
    driver: local
